### ISSUE TITLE
RMETAR crashes while processing METAR in loops

### ISSUE THREAD

**Issue by GreenhouseCH** [jwijffels/RMETAR#1]
RMETAR is a great tool for decoding METARs in R. Unfortunately, it seems that the DLL is generating some problems if you want to massively decode a list of METARs in a loop. 
I couldn't find a workaround for it. Here is a reproducible example. There is a tendency that RStudio crashes earlier than the R binary itself - with earlier I mean: with shorter loops.

Is there any fix for that? 

I already tried to introduce Sys.sleep() prompts without success. 

The problem happens both in i386 and x64 R interfaces, on all Windows 10 systems I used up to now. 

Kind regards

Bertrán
[minimal.example.R.zip](https://github.com/jwijffels/RMETAR/files/1251625/minimal.example.R.zip)

**Comment by jwijffels** [comment]
Hi Bertran, I can't reproduce this on my Linux machine.

**Comment by GreenhouseCH** [comment]
Hello

Thanks for your rapid reply. Next level: Does this script work with you?
[RMETAR_OGIMET.zip](https://github.com/jwijffels/RMETAR/files/1251665/RMETAR_OGIMET.zip)

**Comment by jwijffels** [comment]
Yes, it does on my machine.

**Comment by GreenhouseCH** [comment]
Allright, do you own a Windows machine? I think it has something to do with the dynamic library.

**Comment by jwijffels** [comment]
yes, but currently not sitting behind one.

**Comment by GreenhouseCH** [comment]
It would be great if you could test it there and report.

**Comment by jwijffels** [comment]
I can confirm the crash on Windows.

**Comment by GreenhouseCH** [comment]
Thanks for checking. Is there any way to fix this?

**Comment by jwijffels** [comment]
Yes, but it is on a long todo list

**Comment by GreenhouseCH** [comment]
Allright. Would be great.

**Comment by jwijffels** [comment]
I think the best to fix this is to rewrite this using Rcpp but this requires quite some work.

**Comment by andrie** [comment]
I think we can close this, since it will be addressed by #8

**Comment by jwijffels** [comment]
Yes DEV version which uses https://github.com/flightaware/mdsplib no longer crashes on large number of METAR reports.
